# Generated by Django 5.2.3 on 2025-06-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=3)),
                ('target', models.CharField(max_length=3)),
                ('rate', models.FloatField()),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('base', 'target', 'date')},
            },
        ),
    ]
